version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tabebui
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20

  server:
    build: ./server
    container_name: app_server
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: app
      CORS_ORIGINS: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  front:
    build: ./front
    container_name: app_front
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "5173:5173"
    environment:
      # API への呼び出しは Vite の devServer プロキシで /api -> server:8000 にルーティングします
      NODE_ENV: development
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data: {}
